#!/bin/bash

set -e

echo
echo "===> Build started at $(date)"
echo
START=$SECONDS

# Unconditionally print elapsed build time at exit
function finish {
  echo "===> Elapsed time: $(($SECONDS - $START)) seconds"
}
trap finish EXIT

echo "---> Preparing source..."
mkdir -p $SOURCE

cp -Rf /tmp/src/. $SOURCE

cd $SOURCE

echo "---> Downloading dependencies..."
go get -v ./...

echo "---> Installing revel..."
go get github.com/golang/dep/cmd/dep
go get github.com/revel/revel
go get github.com/revel/cmd/revel

echo "---> Building application source with revel..."
$GOBIN/revel build main/ $GOBIN/build prod

echo "===> Build completed at $(date)"

# Fix source directory permissions
fix-permissions ./
